# Site settings
title:       Robert Carosi
email:       robert@carosi.nl
author:      Robert Carosi
description: "Adventures of a 23 year old."
baseurl:     ""
url:         "http://nov1n.github.io"

# Google analytics
google_analytics: "UA-62698757-1"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: nov1n

# Social icons
include_icons: true
show_social_icons: false
github_username: nov1n
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username: robertcarosi
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
permalink:    pretty
paginate:     3
sass:
  compressed: true
